[package]
name = "suricata"
version = "4.0.1"

[lib]
crate-type = ["staticlib"]

[profile.release]
debug = true

[features]
lua = []
experimental = ["ntp-parser"]
strict = []

[dependencies]
nom = "~3.0"
libc = "~0.2.0"
crc = "~1.4.0"

ntp-parser = { version = "^0", optional = true }
